### ISSUE TITLE
Luarocks distribution

### ISSUE THREAD

**Issue by subnetmarco** [adobe-apiplatform/api-gateway-aws#10]
If this library could be published as a [Luarocks](luarocks.org) distribution, it would make it easier to include it into projects.

**Comment by ddragosd** [comment]
thanks @thefosk . We'll include Luarocks distributions in our plans. Is this urgent for you ?

**Comment by subnetmarco** [comment]
The community is currently contributing to a AWS Lambda plugin for Kong - having it on Luarocks would definitely help https://github.com/Mashape/kong/pull/1187 being merged into the next release. Thanks for what you can do.

**Comment by subnetmarco** [comment]
@ddragosd any updates?

**Comment by ddragosd** [comment]
@thefosk thanks for following up. It wasn't clear the priority for this. We'll probably add support for both [luarocks](https://luarocks.org/) and [opm](https://github.com/openresty/opm).  I'll get back with an update soon.

**Comment by ddragosd** [comment]
@thefosk see http://luarocks.org/modules/adobe-api-platform/lua-api-gateway-aws 
The PR is: #15 .

**Comment by ddragosd** [comment]
module [lua-api-gateway-aws](http://luarocks.org/modules/adobe-api-platform/lua-api-gateway-aws) exists in luarocks.
