### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by nilnor** [adobe-apiplatform/api-gateway-aws#18]
It's not readily apparent what license the code is released under. Some files appears to released under the Apache license, but others lack copyright notice altogether. The repository lacks a LICENSE, and there's no mention of a license in the README. In short, this should be made explicit at some location.

**Comment by ddragosd** [comment]
@nilnor thanks for bringing this up. I'm adding the Apache 2.0 license that is missing.

**Comment by ddragosd** [comment]
done
